### ISSUE TITLE
Unable to run SimilarityCalculation on Hadoop mode

### ISSUE THREAD

**Issue by thammegowda** [USCDataScience/pooled_time_series#6]
Following the instructions in the README file to run in hadoop mode 
[Here](https://github.com/USCDataScience/hadoop-pot/blob/53fe94bac0b0a440e6d40fc7018409609a7123fc/README.md#running-individual-jobs) : 
It says:

```
# Run the meanChiSquaredDistance job
hadoop jar target/pooled-time-series-1.0-SNAPSHOT-jar-with-dependencies.jar \
    org.pooledtimeseries.SimilarityCalculation SimilarityInput/ MeanChiOutput/
```

However, the code expects more than 2 arguments. [Check this line](https://github.com/USCDataScience/hadoop-pot/blob/e5fbb054010aa73bc7dac2356e654017b4bcd9af/src/main/java/org/pooledtimeseries/SimilarityCalculation.java#L115)

The error I am getting : 

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
    at org.pooledtimeseries.SimilarityCalculation.main(SimilarityCalculation.java:115)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```

Please fix or update the README

**Comment by chrismattmann** [comment]
@smadha what's up here

**Comment by chrismattmann** [comment]
fixed in https://github.com/USCDataScience/hadoop-pot/commit/40129dd0e2da8060d4c48324767bdd25837d86b1
